// <auto-generated />
using System;
using FilmKatalogus.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmKatalogus.Api.Data.Migrations
{
    [DbContext(typeof(FilmKatalogusContext))]
    [Migration("20260324084212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("FilmKatalogus.Api.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Hossz")
                        .HasColumnType("TEXT");

                    b.Property<double>("ImDbErtekeles")
                        .HasColumnType("REAL");

                    b.Property<int>("MegjelenesiDatum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MufajId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NyelvId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rendezo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SajatErtekeles")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MufajId");

                    b.HasIndex("NyelvId");

                    b.ToTable("Filmek");
                });

            modelBuilder.Entity("FilmKatalogus.Api.Models.Mufaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mufajok");
                });

            modelBuilder.Entity("FilmKatalogus.Api.Models.Nyelv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nyelvek");
                });

            modelBuilder.Entity("FilmKatalogus.Api.Models.Film", b =>
                {
                    b.HasOne("FilmKatalogus.Api.Models.Mufaj", "Mufaj")
                        .WithMany()
                        .HasForeignKey("MufajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmKatalogus.Api.Models.Nyelv", "Nyelv")
                        .WithMany()
                        .HasForeignKey("NyelvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mufaj");

                    b.Navigation("Nyelv");
                });
#pragma warning restore 612, 618
        }
    }
}
