// <auto-generated />
using System;
using FilmKatalogus.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmKatalogus.Api.Data.Migrations
{
    [DbContext(typeof(FilmKatalogusContext))]
    [Migration("20260324084212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("FilmKatalogus.Api.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rendezo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<int>("MufajId")
                        .HasColumnType("INTEGER");
                    b.Property<TimeOnly>("Hossz")
                        .HasColumnType("TEXT");
                    b.Property<string>("Nyelv")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<DateOnly>("MegjelenesiDatum")
                        .HasColumnType("TEXT");
                    b.Property<double>("ImDbErtekeles")
                        .HasColumnType("REAL");
                    b.Property<double>("SajatErtekeles")
                        .HasColumnType("REAL");
                    b.HasKey("Id");

                    b.HasIndex("MufajId");

                    b.ToTable("Filmek");
                });

            modelBuilder.Entity("FilmKatalogus.Api.Entities.Mufaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mufajok");
                    b.HasData(
                        new { Id = 1, Name = "Action" },
            new { Id = 2, Name = "Adventure" },
            new { Id = 3, Name = "Animated" },
            new { Id = 4, Name = "Comedy" },
            new { Id = 5, Name = "Drama" },
            new { Id = 6, Name = "Fantasy" },
            new { Id = 7, Name = "Historical" },
            new { Id = 8, Name = "Horror" },
            new { Id = 9, Name = "Melodrama" },
            new { Id = 10, Name = "Musical" },
            new { Id = 11, Name = "Noir" },
            new { Id = 12, Name = "Romance" },
            new { Id = 13, Name = "Science fiction" },
            new { Id = 14, Name = "Thriller" },
            new { Id = 15, Name = "Western" }
                    );
                });

                modelBuilder.Entity("FilmKatalogus.Api.Entities.Szineszek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Szineszek");
                });
                modelBuilder.Entity("FilmKatalogus.Api.Entities.FilmCast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SzineszId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("filmCim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FilmCast");
                });


            modelBuilder.Entity("FilmKatalogus.Api.Entities.Film", b =>
                {
                    b.HasOne("FilmKatalogus.Api.Entities.Mufaj", "Mufaj")
                        .WithMany()
                        .HasForeignKey("MufajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mufaj");

                });
            modelBuilder.Entity("FilmKatalogus.Api.Entities.FilmCast", b =>
                {
                    b.HasOne("FilmKatalogus.Api.Entities.Szineszek", "Szineszek")
                        .WithMany()
                        .HasForeignKey("SzineszId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szineszek");

                });
                modelBuilder.Entity("FilmKatalogus.Api.Entities.FilmCast", b =>
                {
                    b.HasOne("FilmKatalogus.Api.Entities.Film", "Film")
                        .WithMany()
                        .HasForeignKey("filmCim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                });
#pragma warning restore 612, 618
        }
    }
}
